a = int(input("entrer la valeur de a: "))
b = int(input("entrer la valeur de b: "))
print("le quotient entier de la division est: ", a//b)
print("le quotient reel de la division est: ", a/b)
print("le reste de la division est : ", a%b)
